### ISSUE TITLE
Add way to prevent default messages logged on the console

### ISSUE THREAD

**Issue by taromero** [MiroHibler/meteor-preloader#12]
I found all the logged messages when loading the assets a bit annoying (specially during development).

Is there a way to "mute" them? If not, I would like that option :).

**Comment by MiroHibler** [comment]
Yes, that's high on the priority list.

Stay tuned ;)

**Comment by juho** [comment]
+1!

**Comment by taromero** [comment]
@MiroHibler I've issued a PR regarding this ticket, could you take a look on it? I currently had fork the project and publish the fix to atmosphere, but it would be nice to just depend on the original lib.

**Comment by tcastelli** [comment]
+1!

**Comment by MiroHibler** [comment]
Solved by https://github.com/MiroHibler/meteor-preloader/commit/6c5ff62f3c403e21f72c663c58dbaefa2c4a7bc7
