### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by rolivav** [MiroHibler/meteor-preloader#28]
I am trying to use this package but I can't seem to make it work. There is something I am not understanding. Is there a chance you could upload an example project with preloader working?

**Comment by MiroHibler** [comment]
Hey @rolivav, could you share your code?

**Comment by MiroHibler** [comment]
Any progress?

If you're okay now, I'm gonna close this issue, ok?

**Comment by rolivav** [comment]
Yeah, sorry, forgot about this. I ended up loading a bunch of libraries with wait-on-lib. I didn't find out what was going on, should have shared the code, but I was in a bit of a hurry to do a prototype.
