### ISSUE TITLE
Error on firefox: Can't flush inside Tracker.autorun

### ISSUE THREAD

**Issue by pwiegers** [MiroHibler/meteor-preloader#32]
Hi,

you [requested](https://forums.meteor.com/t/problem-with-firefox-error-cant-flush-inside-tracker-autorun/22051) for nilsonivano to file a report. As it seems s/he will not do that, I will. :-)

Loading a Meteor site with the preloader installed with Firefox will fail with the error: 

> Can't flush inside Tracker.autorun

If I remove miro:preloader, the error is gone. I'm a /very/ inexperienced Meteor developer, so I do not know what I can do to help, but this is what I observed.

Meteor-verion: 1.3.2
Miro:preloader: 1.2.4
Firefox: 45.01/Ubuntu and OS/X

If I can be of assistence, please let me know :-)

regards,
Paul

**Comment by mkarliner** [comment]
+1 just hit the same problem myself. 
Again, if you need any further information, please ask.

**Comment by mkarliner** [comment]
It looks to me like loadSync  needs to be run inside a Tracker.nonreactive to avoid the flush caused by the XMLHttpRequest.

**Comment by pwiegers** [comment]
Hi @mkarliner ,

as I stated above, I'm a very inexperienced Meteor-dev. So, I have no clue as to do with your comment... :-)
Do you have a new version planned that has this change?
(The issue still crops up - but only on FF?)

regards,

Paul

**Comment by mkarliner** [comment]
Is this a record?
best wishes 
Mike
